# Official docker image.
variables:
  DOCKER_DRIVER: overlay2

image: docker:latest

before_script:
  - docker login -u $DTR_USERNAME -p $DTR_PASSWORD $DTR_SERVER

stages:
  - build
  - deploy

job1:
  stage: build
  script:
    - docker build --pull -t dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":$CI_JOB_ID -t dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":latest .
    - docker push dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":$CI_JOB_ID
    - docker push dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":latest
    - docker rmi dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":$CI_JOB_ID
    - docker rmi dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":latest

job2:
  stage: build
  script:
    - sudo docker login -u $DTR_USERNAME -p $DTR_PASSWORD $DTR_SERVER
    - sudo docker rmi dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":latest
    - sudo docker pull dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":latest
    - sudo docker service update --image dtr.clovett.dtcntr.net/admin/"$CI_PROJECT_NAME":latest hello-node_web
  # variables:
  #   DOCKER_HOST: "tcp://ucp.clovett.dtcntr.net:443"
