version: '3.1'
services:
    web:
        image: dtr.clovett.dtcntr.net/engineering/hello-node
        deploy:
            mode: replicated
            replicas: 2
        healthcheck:
            interval: 10s
            timeout: 5s
            retries: 3
        ports:
            - 8081:8081

    visualizer:
      image: dockersamples/visualizer:stable
      ports:
        - "8088:8088"
      stop_grace_period: 1m30s
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      deploy:
        placement:
          constraints: [node.role == manager]

networks:
    backend:
