version: '3.3'
services:
    web:
      image: dtr.clovett.dtcntr.net/admin/hello-node
      healthcheck:
          interval: 10s
          timeout: 5s
          retries: 3
      ports:
          - 8888:8081
      networks:
          - swarm-overlay
      deploy:
        mode: replicated
        replicas: 2

   visualizer:
     image: dockersamples/visualizer:stable
     ports:
       - "8085:8080"
     stop_grace_period: 1m30s
     volumes:
       - "/var/run/docker.sock:/var/run/docker.sock"
     deploy:
       placement:
         constraints: [node.role == manager]

networks:
  swarm-overlay:
